[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.default]
dependencies = [ "build" ]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
clear = true
command = "cargo"
args = ["build", "--release", "--target", "wasm32-unknown-unknown"]

[tasks.test]
command = "cargo"
args = ["test"]

